### Numpy
Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with collection of mathematical functions to operate on these data structure. 

In [2]:
import numpy as np
print(np.__version__)

2.4.2


In [6]:
import numpy as np 
## creating arrays using numpy

## creating a 1D array

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape) #return shape of the array

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8])
arr2.reshape(2,4) #becomes a 2d array (1 = row, 4 = columns)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
## 2D Array
arr2 = np.array([[12,21,34],[45,87,10]])
print(arr2.shape)
print(arr2)

(2, 3)
[[12 21 34]
 [45 87 10]]


In [ ]:
np.arange(0,10,2).reshape(5,1) #converting a single dimensional array into 2d

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
np.ones((3,4)) #it will have all the elements as 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
## identity matrix
np.eye(3) #diagonal elements will be 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#Attributes of numpy Array

arr = np.array([[1,2,3,],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape) #Output: (2,3)
print("Number of dimensions:",arr.ndim) #Output: 2
print("Size (number of elements):",arr.size) #Output: 6
print("Data type:",arr.dtype) #Output: int62 
print("Item size (in bytes):",arr.itemsize) 


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [34]:
# Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise Addition
print("Addition:",arr1 + arr2)

## Element Wise Subtraction
print("Subtraction:",arr1-arr2)

## Element Wise Multiplication
print("Multiplication:",arr1*arr2)

## Element Wise Division
print("Division:",arr1/arr2)

## Element Wise Modulo
print("Modulo",arr1%arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
Modulo [1 2 3 4 5]


In [37]:
### Universal Function -> Functions that are applied to the entire array
arr = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log)

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
<ufunc 'log'>


In [41]:
## Array slicing and Indexing

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:2,2:])

1
[[3]
 [6]]
[[6]]


In [49]:
print(arr[1:])

[[4 5 6]
 [7 8 9]]


In [51]:
print(arr[1:,2:])

[[6]
 [9]]


In [57]:
## Modify array elements
arr[0,0] = 100
print(arr)


[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [58]:
arr[1:] = 200
print(arr)

[[100   2   3]
 [200 200 200]
 [200 200 200]]
